import { NextRequest, NextResponse } from 'next/server';
import Stripe from 'stripe';
import { getServiceClient } from '../../../lib/supabase';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY || '', {
  apiVersion: '2026-03-25.dahlia',
});

export async function GET(req: NextRequest) {
  try {
    const sessionId = req.nextUrl.searchParams.get('session_id');
    if (!sessionId) {
      return NextResponse.json({ error: 'Missing session_id' }, { status: 400 });
    }

    // Get checkout session from Stripe
    const session = await stripe.checkout.sessions.retrieve(sessionId);
    if (!session || session.status !== 'complete') {
      return NextResponse.json({ error: 'Session not found or incomplete' }, { status: 404 });
    }

    const subscriptionId = session.subscription as string;
    if (!subscriptionId) {
      return NextResponse.json({ error: 'No subscription found' }, { status: 404 });
    }

    // Find the claim code generated by the webhook
    const sb = getServiceClient();
    const { data: claim } = await sb
      .from('membership_claim_codes')
      .select('code, circle_id, is_redeemed')
      .eq('stripe_subscription_id', subscriptionId)
      .maybeSingle();

    if (!claim) {
      // Webhook might not have fired yet — retry after a short delay
      return NextResponse.json({ error: 'Code is being generated. Please refresh in a moment.' }, { status: 202 });
    }

    // Get circle name
    const { data: circle } = await sb
      .from('cooking_circles')
      .select('name')
      .eq('id', claim.circle_id)
      .maybeSingle();

    return NextResponse.json({
      code: claim.code,
      circle_name: circle?.name || 'Premium Circle',
      is_redeemed: claim.is_redeemed,
    });
  } catch (err: any) {
    console.error('[get-claim-code] Error:', err.message);
    return NextResponse.json({ error: 'Failed to retrieve claim code' }, { status: 500 });
  }
}
